name: Claude Code CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      claude_task:
        description: 'Claude task to execute'
        required: false
        default: 'review'

env:
  CLAUDE_PERMISSIONS_MODE: acceptEdits
  CLAUDE_COST_LIMIT_PER_DAY: 2

jobs:
  claude-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Claude CLI
      run: |
        curl -fsSL https://claude-cli.anthropic.com/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Configure Claude
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        claude --version
        echo "Claude CLI configured"
    
    - name: Get PR diff
      id: pr_diff
      run: |
        git diff origin/${{ github.base_ref }}...HEAD > pr_changes.diff
        echo "diff_size=$(wc -c < pr_changes.diff)" >> $GITHUB_OUTPUT
    
    - name: Claude PR Review
      if: steps.pr_diff.outputs.diff_size > 0
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        claude --permission-mode acceptEdits "Review this PR and provide feedback:
        
        $(cat pr_changes.diff | head -5000)
        
        Focus on:
        1. Code quality and best practices
        2. Potential bugs or issues
        3. Performance considerations
        4. Security concerns
        5. Suggestions for improvement" > review.md
    
    - name: Post Review Comment
      if: steps.pr_diff.outputs.diff_size > 0
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const review = fs.readFileSync('review.md', 'utf8');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## Claude Code Review\n\n${review}\n\n---\n*Generated by Claude AI*`
          });

  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd cursor-extension && npm ci
    
    - name: Run linter
      run: npm run lint
      continue-on-error: true
    
    - name: Run tests
      run: npm test
      continue-on-error: true
    
    - name: Build extension
      run: |
        cd cursor-extension
        npm run compile

  auto-fix:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Claude CLI
      run: |
        curl -fsSL https://claude-cli.anthropic.com/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Auto-fix issues
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        # Run linter and capture errors
        npm run lint 2>&1 | tee lint-errors.txt || true
        
        # If there are errors, ask Claude to fix them
        if [ -s lint-errors.txt ]; then
          claude --permission-mode acceptEdits "Fix these linting errors:
          
          $(cat lint-errors.txt)
          
          Apply the fixes directly to the files."
        fi
        
        # Format code
        npm run format || true
    
    - name: Commit fixes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if [ -n "$(git status --porcelain)" ]; then
          git add -A
          git commit -m "fix: auto-fix linting and formatting issues
          
          Co-authored-by: Claude <noreply@anthropic.com>"
          git push
        fi

  claude-task:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.claude_task != ''
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Claude CLI
      run: |
        curl -fsSL https://claude-cli.anthropic.com/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Execute Claude Task
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        claude --permission-mode acceptEdits "${{ github.event.inputs.claude_task }}"
    
    - name: Create PR if changes
      if: success()
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "feat: changes from Claude task execution"
        title: "Claude Task: ${{ github.event.inputs.claude_task }}"
        body: |
          This PR was created by Claude executing the following task:
          
          ```
          ${{ github.event.inputs.claude_task }}
          ```
          
          Please review the changes before merging.
        branch: claude-task-${{ github.run_number }}